// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: ipc.proto

package ipcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Состояние знакомства с пиром.
type Chat_State int32

const (
	Chat_STATE_UNSPECIFIED Chat_State = 0
	Chat_STATE_PENDING_OUT Chat_State = 1 // мы отправили запрос
	Chat_STATE_PENDING_IN  Chat_State = 2 // запрос ждёт нашего решения
	Chat_STATE_CONTACT     Chat_State = 3 // принятый контакт
	Chat_STATE_BLOCKED     Chat_State = 4 // заблокирован
)

// Enum value maps for Chat_State.
var (
	Chat_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING_OUT",
		2: "STATE_PENDING_IN",
		3: "STATE_CONTACT",
		4: "STATE_BLOCKED",
	}
	Chat_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING_OUT": 1,
		"STATE_PENDING_IN":  2,
		"STATE_CONTACT":     3,
		"STATE_BLOCKED":     4,
	}
)

func (x Chat_State) Enum() *Chat_State {
	p := new(Chat_State)
	*p = x
	return p
}

func (x Chat_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chat_State) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_proto_enumTypes[0].Descriptor()
}

func (Chat_State) Type() protoreflect.EnumType {
	return &file_ipc_proto_enumTypes[0]
}

func (x Chat_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chat_State.Descriptor instead.
func (Chat_State) EnumDescriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{17, 0}
}

type Message_Status int32

const (
	Message_STATUS_UNSPECIFIED Message_Status = 0
	Message_STATUS_QUEUED      Message_Status = 1 // в outbox, пир офлайн
	Message_STATUS_SENT        Message_Status = 2 // ушло в сеть, ack не получен
	Message_STATUS_DELIVERED   Message_Status = 3 // ack получателя
)

// Enum value maps for Message_Status.
var (
	Message_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_QUEUED",
		2: "STATUS_SENT",
		3: "STATUS_DELIVERED",
	}
	Message_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_QUEUED":      1,
		"STATUS_SENT":        2,
		"STATUS_DELIVERED":   3,
	}
)

func (x Message_Status) Enum() *Message_Status {
	p := new(Message_Status)
	*p = x
	return p
}

func (x Message_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_proto_enumTypes[1].Descriptor()
}

func (Message_Status) Type() protoreflect.EnumType {
	return &file_ipc_proto_enumTypes[1]
}

func (x Message_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Status.Descriptor instead.
func (Message_Status) EnumDescriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{19, 0}
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Frame_Hello
	//	*Frame_Command
	//	*Frame_Event
	Kind          isFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() isFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Frame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Frame) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Frame) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Frame_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type Frame_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*Frame_Hello) isFrame_Kind() {}

func (*Frame_Command) isFrame_Kind() {}

func (*Frame_Event) isFrame_Kind() {}

// Первое сообщение после установления соединения; токен передаётся
// molvad'у через env при спавне. Несовпадение — немедленный разрыв.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// Команда UI → ядро. id — корреляция с CommandResult.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Command_SendText
	//	*Command_AcceptContact
	//	*Command_RejectContact
	//	*Command_BlockContact
	//	*Command_UnblockContact
	//	*Command_SetAlias
	//	*Command_DeleteMessage
	//	*Command_AddContact
	//	*Command_ListChats
	//	*Command_ListMessages
	//	*Command_MyInvite
	Kind          isCommand_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Command) GetKind() isCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Command) GetSendText() *SendText {
	if x != nil {
		if x, ok := x.Kind.(*Command_SendText); ok {
			return x.SendText
		}
	}
	return nil
}

func (x *Command) GetAcceptContact() *AcceptContact {
	if x != nil {
		if x, ok := x.Kind.(*Command_AcceptContact); ok {
			return x.AcceptContact
		}
	}
	return nil
}

func (x *Command) GetRejectContact() *RejectContact {
	if x != nil {
		if x, ok := x.Kind.(*Command_RejectContact); ok {
			return x.RejectContact
		}
	}
	return nil
}

func (x *Command) GetBlockContact() *BlockContact {
	if x != nil {
		if x, ok := x.Kind.(*Command_BlockContact); ok {
			return x.BlockContact
		}
	}
	return nil
}

func (x *Command) GetUnblockContact() *UnblockContact {
	if x != nil {
		if x, ok := x.Kind.(*Command_UnblockContact); ok {
			return x.UnblockContact
		}
	}
	return nil
}

func (x *Command) GetSetAlias() *SetAlias {
	if x != nil {
		if x, ok := x.Kind.(*Command_SetAlias); ok {
			return x.SetAlias
		}
	}
	return nil
}

func (x *Command) GetDeleteMessage() *DeleteMessage {
	if x != nil {
		if x, ok := x.Kind.(*Command_DeleteMessage); ok {
			return x.DeleteMessage
		}
	}
	return nil
}

func (x *Command) GetAddContact() *AddContact {
	if x != nil {
		if x, ok := x.Kind.(*Command_AddContact); ok {
			return x.AddContact
		}
	}
	return nil
}

func (x *Command) GetListChats() *ListChats {
	if x != nil {
		if x, ok := x.Kind.(*Command_ListChats); ok {
			return x.ListChats
		}
	}
	return nil
}

func (x *Command) GetListMessages() *ListMessages {
	if x != nil {
		if x, ok := x.Kind.(*Command_ListMessages); ok {
			return x.ListMessages
		}
	}
	return nil
}

func (x *Command) GetMyInvite() *MyInvite {
	if x != nil {
		if x, ok := x.Kind.(*Command_MyInvite); ok {
			return x.MyInvite
		}
	}
	return nil
}

type isCommand_Kind interface {
	isCommand_Kind()
}

type Command_SendText struct {
	SendText *SendText `protobuf:"bytes,2,opt,name=send_text,json=sendText,proto3,oneof"`
}

type Command_AcceptContact struct {
	AcceptContact *AcceptContact `protobuf:"bytes,3,opt,name=accept_contact,json=acceptContact,proto3,oneof"`
}

type Command_RejectContact struct {
	RejectContact *RejectContact `protobuf:"bytes,4,opt,name=reject_contact,json=rejectContact,proto3,oneof"`
}

type Command_BlockContact struct {
	BlockContact *BlockContact `protobuf:"bytes,5,opt,name=block_contact,json=blockContact,proto3,oneof"`
}

type Command_UnblockContact struct {
	UnblockContact *UnblockContact `protobuf:"bytes,6,opt,name=unblock_contact,json=unblockContact,proto3,oneof"`
}

type Command_SetAlias struct {
	SetAlias *SetAlias `protobuf:"bytes,7,opt,name=set_alias,json=setAlias,proto3,oneof"`
}

type Command_DeleteMessage struct {
	DeleteMessage *DeleteMessage `protobuf:"bytes,8,opt,name=delete_message,json=deleteMessage,proto3,oneof"`
}

type Command_AddContact struct {
	AddContact *AddContact `protobuf:"bytes,9,opt,name=add_contact,json=addContact,proto3,oneof"`
}

type Command_ListChats struct {
	ListChats *ListChats `protobuf:"bytes,10,opt,name=list_chats,json=listChats,proto3,oneof"`
}

type Command_ListMessages struct {
	ListMessages *ListMessages `protobuf:"bytes,11,opt,name=list_messages,json=listMessages,proto3,oneof"`
}

type Command_MyInvite struct {
	MyInvite *MyInvite `protobuf:"bytes,12,opt,name=my_invite,json=myInvite,proto3,oneof"`
}

func (*Command_SendText) isCommand_Kind() {}

func (*Command_AcceptContact) isCommand_Kind() {}

func (*Command_RejectContact) isCommand_Kind() {}

func (*Command_BlockContact) isCommand_Kind() {}

func (*Command_UnblockContact) isCommand_Kind() {}

func (*Command_SetAlias) isCommand_Kind() {}

func (*Command_DeleteMessage) isCommand_Kind() {}

func (*Command_AddContact) isCommand_Kind() {}

func (*Command_ListChats) isCommand_Kind() {}

func (*Command_ListMessages) isCommand_Kind() {}

func (*Command_MyInvite) isCommand_Kind() {}

type SendText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"` // NodeID
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendText) Reset() {
	*x = SendText{}
	mi := &file_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendText) ProtoMessage() {}

func (x *SendText) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendText.ProtoReflect.Descriptor instead.
func (*SendText) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *SendText) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *SendText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AcceptContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptContact) Reset() {
	*x = AcceptContact{}
	mi := &file_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptContact) ProtoMessage() {}

func (x *AcceptContact) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptContact.ProtoReflect.Descriptor instead.
func (*AcceptContact) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptContact) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

type RejectContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectContact) Reset() {
	*x = RejectContact{}
	mi := &file_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectContact) ProtoMessage() {}

func (x *RejectContact) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectContact.ProtoReflect.Descriptor instead.
func (*RejectContact) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *RejectContact) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

type BlockContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockContact) Reset() {
	*x = BlockContact{}
	mi := &file_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockContact) ProtoMessage() {}

func (x *BlockContact) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockContact.ProtoReflect.Descriptor instead.
func (*BlockContact) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *BlockContact) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

type UnblockContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockContact) Reset() {
	*x = UnblockContact{}
	mi := &file_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockContact) ProtoMessage() {}

func (x *UnblockContact) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockContact.ProtoReflect.Descriptor instead.
func (*UnblockContact) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *UnblockContact) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

type SetAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlias) Reset() {
	*x = SetAlias{}
	mi := &file_ipc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlias) ProtoMessage() {}

func (x *SetAlias) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlias.ProtoReflect.Descriptor instead.
func (*SetAlias) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{8}
}

func (x *SetAlias) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *SetAlias) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type DeleteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	MsgId         []byte                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessage) Reset() {
	*x = DeleteMessage{}
	mi := &file_ipc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessage) ProtoMessage() {}

func (x *DeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessage.ProtoReflect.Descriptor instead.
func (*DeleteMessage) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMessage) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *DeleteMessage) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

// Добавление контакта по инвайт-строке molva://add/...
type AddContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invite        string                 `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContact) Reset() {
	*x = AddContact{}
	mi := &file_ipc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContact) ProtoMessage() {}

func (x *AddContact) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContact.ProtoReflect.Descriptor instead.
func (*AddContact) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{10}
}

func (x *AddContact) GetInvite() string {
	if x != nil {
		return x.Invite
	}
	return ""
}

type ListChats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChats) Reset() {
	*x = ListChats{}
	mi := &file_ipc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChats) ProtoMessage() {}

func (x *ListChats) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChats.ProtoReflect.Descriptor instead.
func (*ListChats) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{11}
}

type ListMessages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Peer  []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	// Пагинация назад от before_seq; 0 — с конца.
	BeforeSeq     uint64 `protobuf:"varint,2,opt,name=before_seq,json=beforeSeq,proto3" json:"before_seq,omitempty"`
	Limit         uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessages) Reset() {
	*x = ListMessages{}
	mi := &file_ipc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessages) ProtoMessage() {}

func (x *ListMessages) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessages.ProtoReflect.Descriptor instead.
func (*ListMessages) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{12}
}

func (x *ListMessages) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *ListMessages) GetBeforeSeq() uint64 {
	if x != nil {
		return x.BeforeSeq
	}
	return 0
}

func (x *ListMessages) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Запрос собственной инвайт-строки; alias — предлагаемое имя для
// получателя инвайта (необязательно).
type MyInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyInvite) Reset() {
	*x = MyInvite{}
	mi := &file_ipc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyInvite) ProtoMessage() {}

func (x *MyInvite) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyInvite.ProtoReflect.Descriptor instead.
func (*MyInvite) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{13}
}

func (x *MyInvite) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

// Событие ядро → UI.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_CommandResult
	//	*Event_MessageReceived
	//	*Event_MessageDelivered
	//	*Event_PresenceChanged
	//	*Event_ContactRequested
	//	*Event_ContactAccepted
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_ipc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{14}
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Kind.(*Event_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *Event) GetMessageReceived() *MessageReceived {
	if x != nil {
		if x, ok := x.Kind.(*Event_MessageReceived); ok {
			return x.MessageReceived
		}
	}
	return nil
}

func (x *Event) GetMessageDelivered() *MessageDelivered {
	if x != nil {
		if x, ok := x.Kind.(*Event_MessageDelivered); ok {
			return x.MessageDelivered
		}
	}
	return nil
}

func (x *Event) GetPresenceChanged() *PresenceChanged {
	if x != nil {
		if x, ok := x.Kind.(*Event_PresenceChanged); ok {
			return x.PresenceChanged
		}
	}
	return nil
}

func (x *Event) GetContactRequested() *ContactRequested {
	if x != nil {
		if x, ok := x.Kind.(*Event_ContactRequested); ok {
			return x.ContactRequested
		}
	}
	return nil
}

func (x *Event) GetContactAccepted() *ContactAccepted {
	if x != nil {
		if x, ok := x.Kind.(*Event_ContactAccepted); ok {
			return x.ContactAccepted
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,1,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type Event_MessageReceived struct {
	MessageReceived *MessageReceived `protobuf:"bytes,2,opt,name=message_received,json=messageReceived,proto3,oneof"`
}

type Event_MessageDelivered struct {
	MessageDelivered *MessageDelivered `protobuf:"bytes,3,opt,name=message_delivered,json=messageDelivered,proto3,oneof"`
}

type Event_PresenceChanged struct {
	PresenceChanged *PresenceChanged `protobuf:"bytes,4,opt,name=presence_changed,json=presenceChanged,proto3,oneof"`
}

type Event_ContactRequested struct {
	ContactRequested *ContactRequested `protobuf:"bytes,5,opt,name=contact_requested,json=contactRequested,proto3,oneof"`
}

type Event_ContactAccepted struct {
	ContactAccepted *ContactAccepted `protobuf:"bytes,6,opt,name=contact_accepted,json=contactAccepted,proto3,oneof"`
}

func (*Event_CommandResult) isEvent_Kind() {}

func (*Event_MessageReceived) isEvent_Kind() {}

func (*Event_MessageDelivered) isEvent_Kind() {}

func (*Event_PresenceChanged) isEvent_Kind() {}

func (*Event_ContactRequested) isEvent_Kind() {}

func (*Event_ContactAccepted) isEvent_Kind() {}

// Ответ на Command с тем же id; для запросов — данные внутри.
type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // пустая строка — успех
	// Types that are valid to be assigned to Data:
	//
	//	*CommandResult_Chats
	//	*CommandResult_Messages
	//	*CommandResult_Sent
	//	*CommandResult_Invite
	Data          isCommandResult_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_ipc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{15}
}

func (x *CommandResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetData() isCommandResult_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandResult) GetChats() *ChatList {
	if x != nil {
		if x, ok := x.Data.(*CommandResult_Chats); ok {
			return x.Chats
		}
	}
	return nil
}

func (x *CommandResult) GetMessages() *MessageList {
	if x != nil {
		if x, ok := x.Data.(*CommandResult_Messages); ok {
			return x.Messages
		}
	}
	return nil
}

func (x *CommandResult) GetSent() *SentMessage {
	if x != nil {
		if x, ok := x.Data.(*CommandResult_Sent); ok {
			return x.Sent
		}
	}
	return nil
}

func (x *CommandResult) GetInvite() *Invite {
	if x != nil {
		if x, ok := x.Data.(*CommandResult_Invite); ok {
			return x.Invite
		}
	}
	return nil
}

type isCommandResult_Data interface {
	isCommandResult_Data()
}

type CommandResult_Chats struct {
	Chats *ChatList `protobuf:"bytes,3,opt,name=chats,proto3,oneof"`
}

type CommandResult_Messages struct {
	Messages *MessageList `protobuf:"bytes,4,opt,name=messages,proto3,oneof"`
}

type CommandResult_Sent struct {
	Sent *SentMessage `protobuf:"bytes,5,opt,name=sent,proto3,oneof"`
}

type CommandResult_Invite struct {
	Invite *Invite `protobuf:"bytes,6,opt,name=invite,proto3,oneof"`
}

func (*CommandResult_Chats) isCommandResult_Data() {}

func (*CommandResult_Messages) isCommandResult_Data() {}

func (*CommandResult_Sent) isCommandResult_Data() {}

func (*CommandResult_Invite) isCommandResult_Data() {}

type ChatList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatList) Reset() {
	*x = ChatList{}
	mi := &file_ipc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatList) ProtoMessage() {}

func (x *ChatList) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatList.ProtoReflect.Descriptor instead.
func (*ChatList) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{16}
}

func (x *ChatList) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	LastMessage   *Message               `protobuf:"bytes,4,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	State         Chat_State             `protobuf:"varint,5,opt,name=state,proto3,enum=molva.ipc.v1.Chat_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_ipc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{17}
}

func (x *Chat) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *Chat) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Chat) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Chat) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *Chat) GetState() Chat_State {
	if x != nil {
		return x.State
	}
	return Chat_STATE_UNSPECIFIED
}

type MessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageList) Reset() {
	*x = MessageList{}
	mi := &file_ipc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageList) ProtoMessage() {}

func (x *MessageList) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageList.ProtoReflect.Descriptor instead.
func (*MessageList) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{18}
}

func (x *MessageList) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         []byte                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Peer          []byte                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"` // собеседник
	Outgoing      bool                   `protobuf:"varint,3,opt,name=outgoing,proto3" json:"outgoing,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"` // пустая, если контент удалён локально
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	SentAt        int64                  `protobuf:"varint,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // unix миллисекунды, локальные часы записи
	Status        Message_Status         `protobuf:"varint,7,opt,name=status,proto3,enum=molva.ipc.v1.Message_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_ipc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{19}
}

func (x *Message) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Message) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *Message) GetOutgoing() bool {
	if x != nil {
		return x.Outgoing
	}
	return false
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Message) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *Message) GetStatus() Message_Status {
	if x != nil {
		return x.Status
	}
	return Message_STATUS_UNSPECIFIED
}

type SentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentMessage) Reset() {
	*x = SentMessage{}
	mi := &file_ipc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentMessage) ProtoMessage() {}

func (x *SentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentMessage.ProtoReflect.Descriptor instead.
func (*SentMessage) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{20}
}

func (x *SentMessage) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Invite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invite        string                 `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"` // molva://add/...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invite) Reset() {
	*x = Invite{}
	mi := &file_ipc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite.ProtoReflect.Descriptor instead.
func (*Invite) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{21}
}

func (x *Invite) GetInvite() string {
	if x != nil {
		return x.Invite
	}
	return ""
}

type MessageReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReceived) Reset() {
	*x = MessageReceived{}
	mi := &file_ipc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReceived) ProtoMessage() {}

func (x *MessageReceived) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReceived.ProtoReflect.Descriptor instead.
func (*MessageReceived) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{22}
}

func (x *MessageReceived) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageDelivered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	MsgId         []byte                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDelivered) Reset() {
	*x = MessageDelivered{}
	mi := &file_ipc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDelivered) ProtoMessage() {}

func (x *MessageDelivered) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDelivered.ProtoReflect.Descriptor instead.
func (*MessageDelivered) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{23}
}

func (x *MessageDelivered) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *MessageDelivered) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

type PresenceChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceChanged) Reset() {
	*x = PresenceChanged{}
	mi := &file_ipc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceChanged) ProtoMessage() {}

func (x *PresenceChanged) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceChanged.ProtoReflect.Descriptor instead.
func (*PresenceChanged) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{24}
}

func (x *PresenceChanged) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *PresenceChanged) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type ContactRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Peer           []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	SuggestedAlias string                 `protobuf:"bytes,2,opt,name=suggested_alias,json=suggestedAlias,proto3" json:"suggested_alias,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContactRequested) Reset() {
	*x = ContactRequested{}
	mi := &file_ipc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequested) ProtoMessage() {}

func (x *ContactRequested) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequested.ProtoReflect.Descriptor instead.
func (*ContactRequested) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{25}
}

func (x *ContactRequested) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *ContactRequested) GetSuggestedAlias() string {
	if x != nil {
		return x.SuggestedAlias
	}
	return ""
}

type ContactAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          []byte                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactAccepted) Reset() {
	*x = ContactAccepted{}
	mi := &file_ipc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactAccepted) ProtoMessage() {}

func (x *ContactAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactAccepted.ProtoReflect.Descriptor instead.
func (*ContactAccepted) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{26}
}

func (x *ContactAccepted) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

var File_ipc_proto protoreflect.FileDescriptor

const file_ipc_proto_rawDesc = "" +
	"\n" +
	"\tipc.proto\x12\fmolva.ipc.v1\"\x9c\x01\n" +
	"\x05Frame\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.molva.ipc.v1.HelloH\x00R\x05hello\x121\n" +
	"\acommand\x18\x02 \x01(\v2\x15.molva.ipc.v1.CommandH\x00R\acommand\x12+\n" +
	"\x05event\x18\x03 \x01(\v2\x13.molva.ipc.v1.EventH\x00R\x05eventB\x06\n" +
	"\x04kind\"\x1d\n" +
	"\x05Hello\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"\xde\x05\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x125\n" +
	"\tsend_text\x18\x02 \x01(\v2\x16.molva.ipc.v1.SendTextH\x00R\bsendText\x12D\n" +
	"\x0eaccept_contact\x18\x03 \x01(\v2\x1b.molva.ipc.v1.AcceptContactH\x00R\racceptContact\x12D\n" +
	"\x0ereject_contact\x18\x04 \x01(\v2\x1b.molva.ipc.v1.RejectContactH\x00R\rrejectContact\x12A\n" +
	"\rblock_contact\x18\x05 \x01(\v2\x1a.molva.ipc.v1.BlockContactH\x00R\fblockContact\x12G\n" +
	"\x0funblock_contact\x18\x06 \x01(\v2\x1c.molva.ipc.v1.UnblockContactH\x00R\x0eunblockContact\x125\n" +
	"\tset_alias\x18\a \x01(\v2\x16.molva.ipc.v1.SetAliasH\x00R\bsetAlias\x12D\n" +
	"\x0edelete_message\x18\b \x01(\v2\x1b.molva.ipc.v1.DeleteMessageH\x00R\rdeleteMessage\x12;\n" +
	"\vadd_contact\x18\t \x01(\v2\x18.molva.ipc.v1.AddContactH\x00R\n" +
	"addContact\x128\n" +
	"\n" +
	"list_chats\x18\n" +
	" \x01(\v2\x17.molva.ipc.v1.ListChatsH\x00R\tlistChats\x12A\n" +
	"\rlist_messages\x18\v \x01(\v2\x1a.molva.ipc.v1.ListMessagesH\x00R\flistMessages\x125\n" +
	"\tmy_invite\x18\f \x01(\v2\x16.molva.ipc.v1.MyInviteH\x00R\bmyInviteB\x06\n" +
	"\x04kind\"2\n" +
	"\bSendText\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"#\n" +
	"\rAcceptContact\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\"#\n" +
	"\rRejectContact\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\"\"\n" +
	"\fBlockContact\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\"$\n" +
	"\x0eUnblockContact\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\"4\n" +
	"\bSetAlias\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\":\n" +
	"\rDeleteMessage\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\fR\x05msgId\"$\n" +
	"\n" +
	"AddContact\x12\x16\n" +
	"\x06invite\x18\x01 \x01(\tR\x06invite\"\v\n" +
	"\tListChats\"W\n" +
	"\fListMessages\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\x12\x1d\n" +
	"\n" +
	"before_seq\x18\x02 \x01(\x04R\tbeforeSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\" \n" +
	"\bMyInvite\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\xd7\x03\n" +
	"\x05Event\x12D\n" +
	"\x0ecommand_result\x18\x01 \x01(\v2\x1b.molva.ipc.v1.CommandResultH\x00R\rcommandResult\x12J\n" +
	"\x10message_received\x18\x02 \x01(\v2\x1d.molva.ipc.v1.MessageReceivedH\x00R\x0fmessageReceived\x12M\n" +
	"\x11message_delivered\x18\x03 \x01(\v2\x1e.molva.ipc.v1.MessageDeliveredH\x00R\x10messageDelivered\x12J\n" +
	"\x10presence_changed\x18\x04 \x01(\v2\x1d.molva.ipc.v1.PresenceChangedH\x00R\x0fpresenceChanged\x12M\n" +
	"\x11contact_requested\x18\x05 \x01(\v2\x1e.molva.ipc.v1.ContactRequestedH\x00R\x10contactRequested\x12J\n" +
	"\x10contact_accepted\x18\x06 \x01(\v2\x1d.molva.ipc.v1.ContactAcceptedH\x00R\x0fcontactAcceptedB\x06\n" +
	"\x04kind\"\x87\x02\n" +
	"\rCommandResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x05chats\x18\x03 \x01(\v2\x16.molva.ipc.v1.ChatListH\x00R\x05chats\x127\n" +
	"\bmessages\x18\x04 \x01(\v2\x19.molva.ipc.v1.MessageListH\x00R\bmessages\x12/\n" +
	"\x04sent\x18\x05 \x01(\v2\x19.molva.ipc.v1.SentMessageH\x00R\x04sent\x12.\n" +
	"\x06invite\x18\x06 \x01(\v2\x14.molva.ipc.v1.InviteH\x00R\x06inviteB\x06\n" +
	"\x04data\"4\n" +
	"\bChatList\x12(\n" +
	"\x05chats\x18\x01 \x03(\v2\x12.molva.ipc.v1.ChatR\x05chats\"\xa5\x02\n" +
	"\x04Chat\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x128\n" +
	"\flast_message\x18\x04 \x01(\v2\x15.molva.ipc.v1.MessageR\vlastMessage\x12.\n" +
	"\x05state\x18\x05 \x01(\x0e2\x18.molva.ipc.v1.Chat.StateR\x05state\"q\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STATE_PENDING_OUT\x10\x01\x12\x14\n" +
	"\x10STATE_PENDING_IN\x10\x02\x12\x11\n" +
	"\rSTATE_CONTACT\x10\x03\x12\x11\n" +
	"\rSTATE_BLOCKED\x10\x04\"@\n" +
	"\vMessageList\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.molva.ipc.v1.MessageR\bmessages\"\xa9\x02\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\fR\x05msgId\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\fR\x04peer\x12\x1a\n" +
	"\boutgoing\x18\x03 \x01(\bR\boutgoing\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x17\n" +
	"\asent_at\x18\x06 \x01(\x03R\x06sentAt\x124\n" +
	"\x06status\x18\a \x01(\x0e2\x1c.molva.ipc.v1.Message.StatusR\x06status\"Z\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_QUEUED\x10\x01\x12\x0f\n" +
	"\vSTATUS_SENT\x10\x02\x12\x14\n" +
	"\x10STATUS_DELIVERED\x10\x03\">\n" +
	"\vSentMessage\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.molva.ipc.v1.MessageR\amessage\" \n" +
	"\x06Invite\x12\x16\n" +
	"\x06invite\x18\x01 \x01(\tR\x06invite\"B\n" +
	"\x0fMessageReceived\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.molva.ipc.v1.MessageR\amessage\"=\n" +
	"\x10MessageDelivered\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\fR\x05msgId\"=\n" +
	"\x0fPresenceChanged\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\"O\n" +
	"\x10ContactRequested\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peer\x12'\n" +
	"\x0fsuggested_alias\x18\x02 \x01(\tR\x0esuggestedAlias\"%\n" +
	"\x0fContactAccepted\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\fR\x04peerB(Z&github.com/udisondev/molva/proto/ipcpbb\x06proto3"

var (
	file_ipc_proto_rawDescOnce sync.Once
	file_ipc_proto_rawDescData []byte
)

func file_ipc_proto_rawDescGZIP() []byte {
	file_ipc_proto_rawDescOnce.Do(func() {
		file_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipc_proto_rawDesc), len(file_ipc_proto_rawDesc)))
	})
	return file_ipc_proto_rawDescData
}

var file_ipc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_ipc_proto_goTypes = []any{
	(Chat_State)(0),          // 0: molva.ipc.v1.Chat.State
	(Message_Status)(0),      // 1: molva.ipc.v1.Message.Status
	(*Frame)(nil),            // 2: molva.ipc.v1.Frame
	(*Hello)(nil),            // 3: molva.ipc.v1.Hello
	(*Command)(nil),          // 4: molva.ipc.v1.Command
	(*SendText)(nil),         // 5: molva.ipc.v1.SendText
	(*AcceptContact)(nil),    // 6: molva.ipc.v1.AcceptContact
	(*RejectContact)(nil),    // 7: molva.ipc.v1.RejectContact
	(*BlockContact)(nil),     // 8: molva.ipc.v1.BlockContact
	(*UnblockContact)(nil),   // 9: molva.ipc.v1.UnblockContact
	(*SetAlias)(nil),         // 10: molva.ipc.v1.SetAlias
	(*DeleteMessage)(nil),    // 11: molva.ipc.v1.DeleteMessage
	(*AddContact)(nil),       // 12: molva.ipc.v1.AddContact
	(*ListChats)(nil),        // 13: molva.ipc.v1.ListChats
	(*ListMessages)(nil),     // 14: molva.ipc.v1.ListMessages
	(*MyInvite)(nil),         // 15: molva.ipc.v1.MyInvite
	(*Event)(nil),            // 16: molva.ipc.v1.Event
	(*CommandResult)(nil),    // 17: molva.ipc.v1.CommandResult
	(*ChatList)(nil),         // 18: molva.ipc.v1.ChatList
	(*Chat)(nil),             // 19: molva.ipc.v1.Chat
	(*MessageList)(nil),      // 20: molva.ipc.v1.MessageList
	(*Message)(nil),          // 21: molva.ipc.v1.Message
	(*SentMessage)(nil),      // 22: molva.ipc.v1.SentMessage
	(*Invite)(nil),           // 23: molva.ipc.v1.Invite
	(*MessageReceived)(nil),  // 24: molva.ipc.v1.MessageReceived
	(*MessageDelivered)(nil), // 25: molva.ipc.v1.MessageDelivered
	(*PresenceChanged)(nil),  // 26: molva.ipc.v1.PresenceChanged
	(*ContactRequested)(nil), // 27: molva.ipc.v1.ContactRequested
	(*ContactAccepted)(nil),  // 28: molva.ipc.v1.ContactAccepted
}
var file_ipc_proto_depIdxs = []int32{
	3,  // 0: molva.ipc.v1.Frame.hello:type_name -> molva.ipc.v1.Hello
	4,  // 1: molva.ipc.v1.Frame.command:type_name -> molva.ipc.v1.Command
	16, // 2: molva.ipc.v1.Frame.event:type_name -> molva.ipc.v1.Event
	5,  // 3: molva.ipc.v1.Command.send_text:type_name -> molva.ipc.v1.SendText
	6,  // 4: molva.ipc.v1.Command.accept_contact:type_name -> molva.ipc.v1.AcceptContact
	7,  // 5: molva.ipc.v1.Command.reject_contact:type_name -> molva.ipc.v1.RejectContact
	8,  // 6: molva.ipc.v1.Command.block_contact:type_name -> molva.ipc.v1.BlockContact
	9,  // 7: molva.ipc.v1.Command.unblock_contact:type_name -> molva.ipc.v1.UnblockContact
	10, // 8: molva.ipc.v1.Command.set_alias:type_name -> molva.ipc.v1.SetAlias
	11, // 9: molva.ipc.v1.Command.delete_message:type_name -> molva.ipc.v1.DeleteMessage
	12, // 10: molva.ipc.v1.Command.add_contact:type_name -> molva.ipc.v1.AddContact
	13, // 11: molva.ipc.v1.Command.list_chats:type_name -> molva.ipc.v1.ListChats
	14, // 12: molva.ipc.v1.Command.list_messages:type_name -> molva.ipc.v1.ListMessages
	15, // 13: molva.ipc.v1.Command.my_invite:type_name -> molva.ipc.v1.MyInvite
	17, // 14: molva.ipc.v1.Event.command_result:type_name -> molva.ipc.v1.CommandResult
	24, // 15: molva.ipc.v1.Event.message_received:type_name -> molva.ipc.v1.MessageReceived
	25, // 16: molva.ipc.v1.Event.message_delivered:type_name -> molva.ipc.v1.MessageDelivered
	26, // 17: molva.ipc.v1.Event.presence_changed:type_name -> molva.ipc.v1.PresenceChanged
	27, // 18: molva.ipc.v1.Event.contact_requested:type_name -> molva.ipc.v1.ContactRequested
	28, // 19: molva.ipc.v1.Event.contact_accepted:type_name -> molva.ipc.v1.ContactAccepted
	18, // 20: molva.ipc.v1.CommandResult.chats:type_name -> molva.ipc.v1.ChatList
	20, // 21: molva.ipc.v1.CommandResult.messages:type_name -> molva.ipc.v1.MessageList
	22, // 22: molva.ipc.v1.CommandResult.sent:type_name -> molva.ipc.v1.SentMessage
	23, // 23: molva.ipc.v1.CommandResult.invite:type_name -> molva.ipc.v1.Invite
	19, // 24: molva.ipc.v1.ChatList.chats:type_name -> molva.ipc.v1.Chat
	21, // 25: molva.ipc.v1.Chat.last_message:type_name -> molva.ipc.v1.Message
	0,  // 26: molva.ipc.v1.Chat.state:type_name -> molva.ipc.v1.Chat.State
	21, // 27: molva.ipc.v1.MessageList.messages:type_name -> molva.ipc.v1.Message
	1,  // 28: molva.ipc.v1.Message.status:type_name -> molva.ipc.v1.Message.Status
	21, // 29: molva.ipc.v1.SentMessage.message:type_name -> molva.ipc.v1.Message
	21, // 30: molva.ipc.v1.MessageReceived.message:type_name -> molva.ipc.v1.Message
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_ipc_proto_init() }
func file_ipc_proto_init() {
	if File_ipc_proto != nil {
		return
	}
	file_ipc_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Hello)(nil),
		(*Frame_Command)(nil),
		(*Frame_Event)(nil),
	}
	file_ipc_proto_msgTypes[2].OneofWrappers = []any{
		(*Command_SendText)(nil),
		(*Command_AcceptContact)(nil),
		(*Command_RejectContact)(nil),
		(*Command_BlockContact)(nil),
		(*Command_UnblockContact)(nil),
		(*Command_SetAlias)(nil),
		(*Command_DeleteMessage)(nil),
		(*Command_AddContact)(nil),
		(*Command_ListChats)(nil),
		(*Command_ListMessages)(nil),
		(*Command_MyInvite)(nil),
	}
	file_ipc_proto_msgTypes[14].OneofWrappers = []any{
		(*Event_CommandResult)(nil),
		(*Event_MessageReceived)(nil),
		(*Event_MessageDelivered)(nil),
		(*Event_PresenceChanged)(nil),
		(*Event_ContactRequested)(nil),
		(*Event_ContactAccepted)(nil),
	}
	file_ipc_proto_msgTypes[15].OneofWrappers = []any{
		(*CommandResult_Chats)(nil),
		(*CommandResult_Messages)(nil),
		(*CommandResult_Sent)(nil),
		(*CommandResult_Invite)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipc_proto_rawDesc), len(file_ipc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipc_proto_goTypes,
		DependencyIndexes: file_ipc_proto_depIdxs,
		EnumInfos:         file_ipc_proto_enumTypes,
		MessageInfos:      file_ipc_proto_msgTypes,
	}.Build()
	File_ipc_proto = out.File
	file_ipc_proto_goTypes = nil
	file_ipc_proto_depIdxs = nil
}
