// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: ratchet.proto

package ratchetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message — одно сообщение Double Ratchet: открытый заголовок + шифртекст.
// Едет payload'ом конверта TYPE_CHAT.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DhPub         []byte                 `protobuf:"bytes,1,opt,name=dh_pub,json=dhPub,proto3" json:"dh_pub,omitempty"` // текущий ratchet-ключ отправителя, X25519 (32 байта)
	Pn            uint32                 `protobuf:"varint,2,opt,name=pn,proto3" json:"pn,omitempty"`                   // длина предыдущей отправной цепочки
	N             uint32                 `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`                     // номер сообщения в текущей цепочке
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`    // ChaCha20-Poly1305, ключ — одноразовый message key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_ratchet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_ratchet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_ratchet_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetDhPub() []byte {
	if x != nil {
		return x.DhPub
	}
	return nil
}

func (x *Message) GetPn() uint32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *Message) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Message) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// Init — первая половина интерактивной инициализации сессии
// (payload конверта TYPE_SESSION_INIT).
type Init struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IkPub         []byte                 `protobuf:"bytes,1,opt,name=ik_pub,json=ikPub,proto3" json:"ik_pub,omitempty"`             // identity-ключ ratchet-слоя инициатора (32 байта)
	EphPub        []byte                 `protobuf:"bytes,2,opt,name=eph_pub,json=ephPub,proto3" json:"eph_pub,omitempty"`          // эфемерный X25519 инициатора (32 байта)
	SessionId     []byte                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 16 случайных байт, связывает init и ack
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init) Reset() {
	*x = Init{}
	mi := &file_ratchet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init) ProtoMessage() {}

func (x *Init) ProtoReflect() protoreflect.Message {
	mi := &file_ratchet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init.ProtoReflect.Descriptor instead.
func (*Init) Descriptor() ([]byte, []int) {
	return file_ratchet_proto_rawDescGZIP(), []int{1}
}

func (x *Init) GetIkPub() []byte {
	if x != nil {
		return x.IkPub
	}
	return nil
}

func (x *Init) GetEphPub() []byte {
	if x != nil {
		return x.EphPub
	}
	return nil
}

func (x *Init) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

// InitAck — ответная половина (payload конверта TYPE_SESSION_INIT_ACK).
type InitAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IkPub         []byte                 `protobuf:"bytes,1,opt,name=ik_pub,json=ikPub,proto3" json:"ik_pub,omitempty"`
	EphPub        []byte                 `protobuf:"bytes,2,opt,name=eph_pub,json=ephPub,proto3" json:"eph_pub,omitempty"`
	SessionId     []byte                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAck) Reset() {
	*x = InitAck{}
	mi := &file_ratchet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAck) ProtoMessage() {}

func (x *InitAck) ProtoReflect() protoreflect.Message {
	mi := &file_ratchet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAck.ProtoReflect.Descriptor instead.
func (*InitAck) Descriptor() ([]byte, []int) {
	return file_ratchet_proto_rawDescGZIP(), []int{2}
}

func (x *InitAck) GetIkPub() []byte {
	if x != nil {
		return x.IkPub
	}
	return nil
}

func (x *InitAck) GetEphPub() []byte {
	if x != nil {
		return x.EphPub
	}
	return nil
}

func (x *InitAck) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

// State — персистентное состояние сессии. Содержит приватные ключи —
// хранится только шифрованным ключом из master-seed.
type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rk            []byte                 `protobuf:"bytes,1,opt,name=rk,proto3" json:"rk,omitempty"`                          // root key (32)
	DhsPriv       []byte                 `protobuf:"bytes,2,opt,name=dhs_priv,json=dhsPriv,proto3" json:"dhs_priv,omitempty"` // наша текущая ratchet-пара, приватная половина (32)
	DhrPub        []byte                 `protobuf:"bytes,3,opt,name=dhr_pub,json=dhrPub,proto3" json:"dhr_pub,omitempty"`    // их текущий ratchet-ключ (32; пусто у респондента до первого приёма)
	Cks           []byte                 `protobuf:"bytes,4,opt,name=cks,proto3" json:"cks,omitempty"`                        // отправная цепочка (32; пусто, пока не начата)
	Ckr           []byte                 `protobuf:"bytes,5,opt,name=ckr,proto3" json:"ckr,omitempty"`                        // приёмная цепочка (32; пусто, пока не начата)
	Ns            uint32                 `protobuf:"varint,6,opt,name=ns,proto3" json:"ns,omitempty"`
	Nr            uint32                 `protobuf:"varint,7,opt,name=nr,proto3" json:"nr,omitempty"`
	Pn            uint32                 `protobuf:"varint,8,opt,name=pn,proto3" json:"pn,omitempty"`
	Ad            []byte                 `protobuf:"bytes,9,opt,name=ad,proto3" json:"ad,omitempty"` // transcript-привязка сессии (associated data)
	Skipped       []*SkippedKey          `protobuf:"bytes,10,rep,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_ratchet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_ratchet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_ratchet_proto_rawDescGZIP(), []int{3}
}

func (x *State) GetRk() []byte {
	if x != nil {
		return x.Rk
	}
	return nil
}

func (x *State) GetDhsPriv() []byte {
	if x != nil {
		return x.DhsPriv
	}
	return nil
}

func (x *State) GetDhrPub() []byte {
	if x != nil {
		return x.DhrPub
	}
	return nil
}

func (x *State) GetCks() []byte {
	if x != nil {
		return x.Cks
	}
	return nil
}

func (x *State) GetCkr() []byte {
	if x != nil {
		return x.Ckr
	}
	return nil
}

func (x *State) GetNs() uint32 {
	if x != nil {
		return x.Ns
	}
	return 0
}

func (x *State) GetNr() uint32 {
	if x != nil {
		return x.Nr
	}
	return 0
}

func (x *State) GetPn() uint32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *State) GetAd() []byte {
	if x != nil {
		return x.Ad
	}
	return nil
}

func (x *State) GetSkipped() []*SkippedKey {
	if x != nil {
		return x.Skipped
	}
	return nil
}

// SkippedKey — отложенный ключ внеочередного сообщения.
type SkippedKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DhPub         []byte                 `protobuf:"bytes,1,opt,name=dh_pub,json=dhPub,proto3" json:"dh_pub,omitempty"`
	N             uint32                 `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	Mk            []byte                 `protobuf:"bytes,3,opt,name=mk,proto3" json:"mk,omitempty"` // message key (32)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkippedKey) Reset() {
	*x = SkippedKey{}
	mi := &file_ratchet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkippedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkippedKey) ProtoMessage() {}

func (x *SkippedKey) ProtoReflect() protoreflect.Message {
	mi := &file_ratchet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkippedKey.ProtoReflect.Descriptor instead.
func (*SkippedKey) Descriptor() ([]byte, []int) {
	return file_ratchet_proto_rawDescGZIP(), []int{4}
}

func (x *SkippedKey) GetDhPub() []byte {
	if x != nil {
		return x.DhPub
	}
	return nil
}

func (x *SkippedKey) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *SkippedKey) GetMk() []byte {
	if x != nil {
		return x.Mk
	}
	return nil
}

var File_ratchet_proto protoreflect.FileDescriptor

const file_ratchet_proto_rawDesc = "" +
	"\n" +
	"\rratchet.proto\x12\x10molva.ratchet.v1\"^\n" +
	"\aMessage\x12\x15\n" +
	"\x06dh_pub\x18\x01 \x01(\fR\x05dhPub\x12\x0e\n" +
	"\x02pn\x18\x02 \x01(\rR\x02pn\x12\f\n" +
	"\x01n\x18\x03 \x01(\rR\x01n\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\"U\n" +
	"\x04Init\x12\x15\n" +
	"\x06ik_pub\x18\x01 \x01(\fR\x05ikPub\x12\x17\n" +
	"\aeph_pub\x18\x02 \x01(\fR\x06ephPub\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\fR\tsessionId\"X\n" +
	"\aInitAck\x12\x15\n" +
	"\x06ik_pub\x18\x01 \x01(\fR\x05ikPub\x12\x17\n" +
	"\aeph_pub\x18\x02 \x01(\fR\x06ephPub\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\fR\tsessionId\"\xe7\x01\n" +
	"\x05State\x12\x0e\n" +
	"\x02rk\x18\x01 \x01(\fR\x02rk\x12\x19\n" +
	"\bdhs_priv\x18\x02 \x01(\fR\adhsPriv\x12\x17\n" +
	"\adhr_pub\x18\x03 \x01(\fR\x06dhrPub\x12\x10\n" +
	"\x03cks\x18\x04 \x01(\fR\x03cks\x12\x10\n" +
	"\x03ckr\x18\x05 \x01(\fR\x03ckr\x12\x0e\n" +
	"\x02ns\x18\x06 \x01(\rR\x02ns\x12\x0e\n" +
	"\x02nr\x18\a \x01(\rR\x02nr\x12\x0e\n" +
	"\x02pn\x18\b \x01(\rR\x02pn\x12\x0e\n" +
	"\x02ad\x18\t \x01(\fR\x02ad\x126\n" +
	"\askipped\x18\n" +
	" \x03(\v2\x1c.molva.ratchet.v1.SkippedKeyR\askipped\"A\n" +
	"\n" +
	"SkippedKey\x12\x15\n" +
	"\x06dh_pub\x18\x01 \x01(\fR\x05dhPub\x12\f\n" +
	"\x01n\x18\x02 \x01(\rR\x01n\x12\x0e\n" +
	"\x02mk\x18\x03 \x01(\fR\x02mkB,Z*github.com/udisondev/molva/proto/ratchetpbb\x06proto3"

var (
	file_ratchet_proto_rawDescOnce sync.Once
	file_ratchet_proto_rawDescData []byte
)

func file_ratchet_proto_rawDescGZIP() []byte {
	file_ratchet_proto_rawDescOnce.Do(func() {
		file_ratchet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratchet_proto_rawDesc), len(file_ratchet_proto_rawDesc)))
	})
	return file_ratchet_proto_rawDescData
}

var file_ratchet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ratchet_proto_goTypes = []any{
	(*Message)(nil),    // 0: molva.ratchet.v1.Message
	(*Init)(nil),       // 1: molva.ratchet.v1.Init
	(*InitAck)(nil),    // 2: molva.ratchet.v1.InitAck
	(*State)(nil),      // 3: molva.ratchet.v1.State
	(*SkippedKey)(nil), // 4: molva.ratchet.v1.SkippedKey
}
var file_ratchet_proto_depIdxs = []int32{
	4, // 0: molva.ratchet.v1.State.skipped:type_name -> molva.ratchet.v1.SkippedKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ratchet_proto_init() }
func file_ratchet_proto_init() {
	if File_ratchet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratchet_proto_rawDesc), len(file_ratchet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ratchet_proto_goTypes,
		DependencyIndexes: file_ratchet_proto_depIdxs,
		MessageInfos:      file_ratchet_proto_msgTypes,
	}.Build()
	File_ratchet_proto = out.File
	file_ratchet_proto_goTypes = nil
	file_ratchet_proto_depIdxs = nil
}
