// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: call.proto

package callpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        []byte                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // 16 случайных байт
	Codecs        []string               `protobuf:"bytes,2,rep,name=codecs,proto3" json:"codecs,omitempty"`               // предлагаемые кодеки ("opus", "vp8")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_call_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_call_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_call_proto_rawDescGZIP(), []int{0}
}

func (x *Offer) GetCallId() []byte {
	if x != nil {
		return x.CallId
	}
	return nil
}

func (x *Offer) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

// Ответ на оффер: принят или отвергнут.
type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        []byte                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_call_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_call_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_call_proto_rawDescGZIP(), []int{1}
}

func (x *Answer) GetCallId() []byte {
	if x != nil {
		return x.CallId
	}
	return nil
}

func (x *Answer) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type Hangup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        []byte                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hangup) Reset() {
	*x = Hangup{}
	mi := &file_call_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hangup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hangup) ProtoMessage() {}

func (x *Hangup) ProtoReflect() protoreflect.Message {
	mi := &file_call_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hangup.ProtoReflect.Descriptor instead.
func (*Hangup) Descriptor() ([]byte, []int) {
	return file_call_proto_rawDescGZIP(), []int{2}
}

func (x *Hangup) GetCallId() []byte {
	if x != nil {
		return x.CallId
	}
	return nil
}

var File_call_proto protoreflect.FileDescriptor

const file_call_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"call.proto\x12\rmolva.call.v1\"8\n" +
	"\x05Offer\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\fR\x06callId\x12\x16\n" +
	"\x06codecs\x18\x02 \x03(\tR\x06codecs\"9\n" +
	"\x06Answer\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\fR\x06callId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"!\n" +
	"\x06Hangup\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\fR\x06callIdB)Z'github.com/udisondev/molva/proto/callpbb\x06proto3"

var (
	file_call_proto_rawDescOnce sync.Once
	file_call_proto_rawDescData []byte
)

func file_call_proto_rawDescGZIP() []byte {
	file_call_proto_rawDescOnce.Do(func() {
		file_call_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_call_proto_rawDesc), len(file_call_proto_rawDesc)))
	})
	return file_call_proto_rawDescData
}

var file_call_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_call_proto_goTypes = []any{
	(*Offer)(nil),  // 0: molva.call.v1.Offer
	(*Answer)(nil), // 1: molva.call.v1.Answer
	(*Hangup)(nil), // 2: molva.call.v1.Hangup
}
var file_call_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_call_proto_init() }
func file_call_proto_init() {
	if File_call_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_call_proto_rawDesc), len(file_call_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_call_proto_goTypes,
		DependencyIndexes: file_call_proto_depIdxs,
		MessageInfos:      file_call_proto_msgTypes,
	}.Build()
	File_call_proto = out.File
	file_call_proto_goTypes = nil
	file_call_proto_depIdxs = nil
}
