// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: blob.proto

package blobpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manifest — описание файла (внутри ratchet-шифртекста).
type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        []byte                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // 16 случайных байт
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                   // имя файла (получатель санитизирует)
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                            // байты
	ChunkSize     uint32                 `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"` // 60 КиБ в v1
	FileKey       []byte                 `protobuf:"bytes,6,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`        // 32 байта, одноразовый ключ чанков
	WholeHash     []byte                 `protobuf:"bytes,7,opt,name=whole_hash,json=wholeHash,proto3" json:"whole_hash,omitempty"`  // BLAKE2b-256 всего файла
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_blob_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetFileId() []byte {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Manifest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Manifest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Manifest) GetFileKey() []byte {
	if x != nil {
		return x.FileKey
	}
	return nil
}

func (x *Manifest) GetWholeHash() []byte {
	if x != nil {
		return x.WholeHash
	}
	return nil
}

// ChunkRequest — оконный запрос недостающих чанков (получатель → отправитель).
type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        []byte                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Indexes       []uint32               `protobuf:"varint,2,rep,packed,name=indexes,proto3" json:"indexes,omitempty"` // ≤ 64 за запрос
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_blob_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkRequest) GetFileId() []byte {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *ChunkRequest) GetIndexes() []uint32 {
	if x != nil {
		return x.Indexes
	}
	return nil
}

// Chunk — один чанк (отправитель → получатель), payload зашифрован
// файловым ключом.
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        []byte                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_blob_proto_rawDescGZIP(), []int{2}
}

func (x *Chunk) GetFileId() []byte {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *Chunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_blob_proto protoreflect.FileDescriptor

const file_blob_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"blob.proto\x12\rmolva.blob.v1\"\xb8\x01\n" +
	"\bManifest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\fR\x06fileId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\rR\tchunkSize\x12\x19\n" +
	"\bfile_key\x18\x06 \x01(\fR\afileKey\x12\x1d\n" +
	"\n" +
	"whole_hash\x18\a \x01(\fR\twholeHash\"A\n" +
	"\fChunkRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\fR\x06fileId\x12\x18\n" +
	"\aindexes\x18\x02 \x03(\rR\aindexes\"P\n" +
	"\x05Chunk\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\fR\x06fileId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB)Z'github.com/udisondev/molva/proto/blobpbb\x06proto3"

var (
	file_blob_proto_rawDescOnce sync.Once
	file_blob_proto_rawDescData []byte
)

func file_blob_proto_rawDescGZIP() []byte {
	file_blob_proto_rawDescOnce.Do(func() {
		file_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blob_proto_rawDesc), len(file_blob_proto_rawDesc)))
	})
	return file_blob_proto_rawDescData
}

var file_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blob_proto_goTypes = []any{
	(*Manifest)(nil),     // 0: molva.blob.v1.Manifest
	(*ChunkRequest)(nil), // 1: molva.blob.v1.ChunkRequest
	(*Chunk)(nil),        // 2: molva.blob.v1.Chunk
}
var file_blob_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blob_proto_init() }
func file_blob_proto_init() {
	if File_blob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blob_proto_rawDesc), len(file_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blob_proto_goTypes,
		DependencyIndexes: file_blob_proto_depIdxs,
		MessageInfos:      file_blob_proto_msgTypes,
	}.Build()
	File_blob_proto = out.File
	file_blob_proto_goTypes = nil
	file_blob_proto_depIdxs = nil
}
