// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: envelope.proto

package envelopepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_UNSPECIFIED Type = 0
	// Подтверждение приёма: payload = msg_id подтверждаемого конверта.
	Type_TYPE_ACK Type = 1
	// Presence: пустой payload, мимо outbox и истории.
	Type_TYPE_PROBE Type = 2
	Type_TYPE_PONG  Type = 3
	// Знакомство: payload — открытый ContactRequest/ContactAccept.
	Type_TYPE_CONTACT_REQUEST Type = 4
	Type_TYPE_CONTACT_ACCEPT  Type = 5
	// Интерактивная инициализация Double Ratchet по прямому каналу.
	Type_TYPE_SESSION_INIT     Type = 6
	Type_TYPE_SESSION_INIT_ACK Type = 7
	// Личное сообщение: payload — ratchet-сообщение (заголовок + ciphertext).
	Type_TYPE_CHAT Type = 8
	// Групповое сообщение: payload — sender-key ciphertext + подпись.
	Type_TYPE_GROUP Type = 9
	// Файловый манифест: payload — ratchet-сообщение с Manifest внутри.
	Type_TYPE_FILE_MANIFEST Type = 10
	// Оконный запрос чанков: открытый ChunkRequest, мимо outbox и дедупа
	// (pull сам ретраит — молчание лечится повтором запроса).
	Type_TYPE_FILE_CHUNK_REQ Type = 11
	// Чанк файла: открытый Chunk (контент зашифрован файловым ключом).
	Type_TYPE_FILE_CHUNK Type = 12
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		1:  "TYPE_ACK",
		2:  "TYPE_PROBE",
		3:  "TYPE_PONG",
		4:  "TYPE_CONTACT_REQUEST",
		5:  "TYPE_CONTACT_ACCEPT",
		6:  "TYPE_SESSION_INIT",
		7:  "TYPE_SESSION_INIT_ACK",
		8:  "TYPE_CHAT",
		9:  "TYPE_GROUP",
		10: "TYPE_FILE_MANIFEST",
		11: "TYPE_FILE_CHUNK_REQ",
		12: "TYPE_FILE_CHUNK",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":      0,
		"TYPE_ACK":              1,
		"TYPE_PROBE":            2,
		"TYPE_PONG":             3,
		"TYPE_CONTACT_REQUEST":  4,
		"TYPE_CONTACT_ACCEPT":   5,
		"TYPE_SESSION_INIT":     6,
		"TYPE_SESSION_INIT_ACK": 7,
		"TYPE_CHAT":             8,
		"TYPE_GROUP":            9,
		"TYPE_FILE_MANIFEST":    10,
		"TYPE_FILE_CHUNK_REQ":   11,
		"TYPE_FILE_CHUNK":       12,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope — единица обмена между узлами molva поверх nodenet.
// Уровень надёжности приложения: получатель отвечает ack'ом на каждый
// принятый конверт, отправитель ретраит из персистентного outbox,
// дедупликация — по (originator, msg_id).
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 16 случайных байт; идентификатор для ack и дедупликации.
	MsgId []byte `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Type  Type   `protobuf:"varint,2,opt,name=type,proto3,enum=molva.envelope.v1.Type" json:"type,omitempty"`
	// Per-sender монотонный номер сообщений истории (детект дыр).
	// Служебные конверты (ack, probe, pong) идут с нулём.
	FromSeq uint64 `protobuf:"varint,3,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	// Лампортова метка для слияния порядка отображения в группах.
	LamportTs uint64 `protobuf:"varint,4,opt,name=lamport_ts,json=lamportTs,proto3" json:"lamport_ts,omitempty"`
	// Содержимое, зависящее от type: ciphertext ratchet'а/sender key,
	// либо открытый служебный payload (ack — msg_id подтверждаемого).
	Payload       []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Envelope) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *Envelope) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *Envelope) GetLamportTs() uint64 {
	if x != nil {
		return x.LamportTs
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\x11molva.envelope.v1\"\xa2\x01\n" +
	"\bEnvelope\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\fR\x05msgId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.molva.envelope.v1.TypeR\x04type\x12\x19\n" +
	"\bfrom_seq\x18\x03 \x01(\x04R\afromSeq\x12\x1d\n" +
	"\n" +
	"lamport_ts\x18\x04 \x01(\x04R\tlamportTs\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload*\x93\x02\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTYPE_ACK\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_PROBE\x10\x02\x12\r\n" +
	"\tTYPE_PONG\x10\x03\x12\x18\n" +
	"\x14TYPE_CONTACT_REQUEST\x10\x04\x12\x17\n" +
	"\x13TYPE_CONTACT_ACCEPT\x10\x05\x12\x15\n" +
	"\x11TYPE_SESSION_INIT\x10\x06\x12\x19\n" +
	"\x15TYPE_SESSION_INIT_ACK\x10\a\x12\r\n" +
	"\tTYPE_CHAT\x10\b\x12\x0e\n" +
	"\n" +
	"TYPE_GROUP\x10\t\x12\x16\n" +
	"\x12TYPE_FILE_MANIFEST\x10\n" +
	"\x12\x17\n" +
	"\x13TYPE_FILE_CHUNK_REQ\x10\v\x12\x13\n" +
	"\x0fTYPE_FILE_CHUNK\x10\fB-Z+github.com/udisondev/molva/proto/envelopepbb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envelope_proto_goTypes = []any{
	(Type)(0),        // 0: molva.envelope.v1.Type
	(*Envelope)(nil), // 1: molva.envelope.v1.Envelope
}
var file_envelope_proto_depIdxs = []int32{
	0, // 0: molva.envelope.v1.Envelope.type:type_name -> molva.envelope.v1.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
