// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: group.proto

package grouppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Membership — подписанный админом состав группы; новая версия на каждое
// изменение. Каноничная сериализация для подписи — отдельная (не protobuf).
type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       []byte                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 32 случайных байта
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AdminPub      []byte                 `protobuf:"bytes,4,opt,name=admin_pub,json=adminPub,proto3" json:"admin_pub,omitempty"` // Ed25519 админа (создателя)
	Members       [][]byte               `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`                   // NodeID участников, отсортированы байтово
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`               // Ed25519 админа над каноничной формой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{0}
}

func (x *Membership) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *Membership) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Membership) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Membership) GetAdminPub() []byte {
	if x != nil {
		return x.AdminPub
	}
	return nil
}

func (x *Membership) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Membership) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SenderKeyDist — раздача своего sender key: ТЕКУЩЕЕ состояние цепочки
// (новичок не сможет читать историю — цепочка идёт только вперёд).
type SenderKeyDist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       []byte                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Generation    uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`            // растёт при rekey
	ChainKey      []byte                 `protobuf:"bytes,3,opt,name=chain_key,json=chainKey,proto3" json:"chain_key,omitempty"` // 32, текущий
	N             uint32                 `protobuf:"varint,4,opt,name=n,proto3" json:"n,omitempty"`                              // номер следующего сообщения цепочки
	SignPub       []byte                 `protobuf:"bytes,5,opt,name=sign_pub,json=signPub,proto3" json:"sign_pub,omitempty"`    // Ed25519 подписи сообщений этого участника
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderKeyDist) Reset() {
	*x = SenderKeyDist{}
	mi := &file_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyDist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyDist) ProtoMessage() {}

func (x *SenderKeyDist) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyDist.ProtoReflect.Descriptor instead.
func (*SenderKeyDist) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{1}
}

func (x *SenderKeyDist) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *SenderKeyDist) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SenderKeyDist) GetChainKey() []byte {
	if x != nil {
		return x.ChainKey
	}
	return nil
}

func (x *SenderKeyDist) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *SenderKeyDist) GetSignPub() []byte {
	if x != nil {
		return x.SignPub
	}
	return nil
}

// Welcome — приглашение новичку: членство и известные админу текущие
// ключи участников.
type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Membership    *Membership            `protobuf:"bytes,1,opt,name=membership,proto3" json:"membership,omitempty"`
	Keys          []*MemberKey           `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{2}
}

func (x *Welcome) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

func (x *Welcome) GetKeys() []*MemberKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type MemberKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        []byte                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Key           *SenderKeyDist         `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberKey) Reset() {
	*x = MemberKey{}
	mi := &file_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberKey) ProtoMessage() {}

func (x *MemberKey) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberKey.ProtoReflect.Descriptor instead.
func (*MemberKey) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{3}
}

func (x *MemberKey) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *MemberKey) GetKey() *SenderKeyDist {
	if x != nil {
		return x.Key
	}
	return nil
}

// Update — новая версия членства существующим участникам.
type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Membership    *Membership            `protobuf:"bytes,1,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{4}
}

func (x *Update) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

// Message — групповое сообщение (payload конверта TYPE_GROUP, открытый):
// шифртекст под message key отправителя + его подпись.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       []byte                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Generation    uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	N             uint32                 `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 отправителя над каноничной формой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *Message) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Message) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Message) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_group_proto protoreflect.FileDescriptor

const file_group_proto_rawDesc = "" +
	"\n" +
	"\vgroup.proto\x12\x0emolva.group.v1\"\xaa\x01\n" +
	"\n" +
	"Membership\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\fR\agroupId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tadmin_pub\x18\x04 \x01(\fR\badminPub\x12\x18\n" +
	"\amembers\x18\x05 \x03(\fR\amembers\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\x90\x01\n" +
	"\rSenderKeyDist\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\fR\agroupId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\x12\x1b\n" +
	"\tchain_key\x18\x03 \x01(\fR\bchainKey\x12\f\n" +
	"\x01n\x18\x04 \x01(\rR\x01n\x12\x19\n" +
	"\bsign_pub\x18\x05 \x01(\fR\asignPub\"t\n" +
	"\aWelcome\x12:\n" +
	"\n" +
	"membership\x18\x01 \x01(\v2\x1a.molva.group.v1.MembershipR\n" +
	"membership\x12-\n" +
	"\x04keys\x18\x02 \x03(\v2\x19.molva.group.v1.MemberKeyR\x04keys\"T\n" +
	"\tMemberKey\x12\x16\n" +
	"\x06member\x18\x01 \x01(\fR\x06member\x12/\n" +
	"\x03key\x18\x02 \x01(\v2\x1d.molva.group.v1.SenderKeyDistR\x03key\"D\n" +
	"\x06Update\x12:\n" +
	"\n" +
	"membership\x18\x01 \x01(\v2\x1a.molva.group.v1.MembershipR\n" +
	"membership\"\x90\x01\n" +
	"\aMessage\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\fR\agroupId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\x12\f\n" +
	"\x01n\x18\x03 \x01(\rR\x01n\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignatureB*Z(github.com/udisondev/molva/proto/grouppbb\x06proto3"

var (
	file_group_proto_rawDescOnce sync.Once
	file_group_proto_rawDescData []byte
)

func file_group_proto_rawDescGZIP() []byte {
	file_group_proto_rawDescOnce.Do(func() {
		file_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)))
	})
	return file_group_proto_rawDescData
}

var file_group_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_group_proto_goTypes = []any{
	(*Membership)(nil),    // 0: molva.group.v1.Membership
	(*SenderKeyDist)(nil), // 1: molva.group.v1.SenderKeyDist
	(*Welcome)(nil),       // 2: molva.group.v1.Welcome
	(*MemberKey)(nil),     // 3: molva.group.v1.MemberKey
	(*Update)(nil),        // 4: molva.group.v1.Update
	(*Message)(nil),       // 5: molva.group.v1.Message
}
var file_group_proto_depIdxs = []int32{
	0, // 0: molva.group.v1.Welcome.membership:type_name -> molva.group.v1.Membership
	3, // 1: molva.group.v1.Welcome.keys:type_name -> molva.group.v1.MemberKey
	1, // 2: molva.group.v1.MemberKey.key:type_name -> molva.group.v1.SenderKeyDist
	0, // 3: molva.group.v1.Update.membership:type_name -> molva.group.v1.Membership
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_group_proto_init() }
func file_group_proto_init() {
	if File_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group_proto_goTypes,
		DependencyIndexes: file_group_proto_depIdxs,
		MessageInfos:      file_group_proto_msgTypes,
	}.Build()
	File_group_proto = out.File
	file_group_proto_goTypes = nil
	file_group_proto_depIdxs = nil
}
